name: stock-env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - python=3.12
  - pip:
      - -r requirements.txt # use pip libraries for lightweight deployment (no conda install required)
      - -e . # allow to import local modules while editing them
